# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build develop

on:
  push:
    branches: [ignore]
  # pull_request:
  #   branches: [develop]

concurrency:
  group: development
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger vercel hook deploy
        run: wget ${{ secrets.VERCEL_HOOK_STAGING }}
